version: '2.1'

services:
  agent:
    build:
      dockerfile: .buildkite/Dockerfile
      context: ../
    volumes:
      - ../:/go/src/github.com/buildkite/agent:cached
    working_dir: /go/src/github.com/buildkite/agent
    environment:
      - BUILDKITE_BUILD_NUMBER
      - BUILDKITE_JOB_ID
      - "BUILDKITE_AGENT_TAGS=queue=default"
      - "BUILDKITE_BUILD_PATH=/buildkite"
