env:
  DRY_RUN: false # set to true to disable publishing releases

steps:
  - group: "Tests"
    steps:
      - label: ":linux: Linux"
        command: ".buildkite/steps/tests.sh"
        plugins:
          docker-compose#v1.8.0:
            run: agent

      - label: ":windows: Windows"
        trigger: agent-windows
        async: true
        build:
          message: "${BUILDKITE_MESSAGE}"
          commit: "${BUILDKITE_COMMIT}"
          branch: "${BUILDKITE_BRANCH}"

  - wait

  - group: "Build"
    steps:
    - label: ":windows: Windows"
      command: ".buildkite/steps/build-binary.sh windows \${BUILDKITE_MATRIX_ARCH}"
      matrix:
        arch:
         - "386"
         - "amd64"
      artifact_paths: "pkg/*"
      plugins:
        docker-compose#v1.8.0:
          run: agent

    - label: ":linux: Linux"
      command: ".buildkite/steps/build-binary.sh linux \${BUILDKITE_MATRIX_ARCH}"
      matrix:
        arch:
          - "amd64"
          - "386"
          - "arm"
          - "armhf"
          - "arm64"
      artifact_paths: "pkg/*"
      plugins:
        docker-compose#v1.8.0:
          run: agent

    - label: ":mac: macOS"
      command: ".buildkite/steps/build-binary.sh darwin \${BUILDKITE_MATRIX_ARCH}"
      matrix:
        arch:
         - "386"
         - "amd64"
      artifact_paths: "pkg/*"
      plugins:
        docker-compose#v1.8.0:
          run: agent

    - label: ":freebsd: FreeBSD"
      matrix:
        arch:
          - "amd64"
          - "386"
      artifact_paths: "pkg/*"
      plugins:
        docker-compose#v1.8.0:
          run: agent

    - label: ":openbsd: OpenBSD"
      command: ".buildkite/steps/build-binary.sh openbsd \${BUILDKITE_MATRIX_ARCH}"
      matrix:
        arch:
          - "amd64"
          - "386"
      artifact_paths: "pkg/*"
      plugins:
        docker-compose#v1.8.0:
          run: agent

    - label: ":dragonflybsd: amd64"
      command: ".buildkite/steps/build-binary.sh dragonfly \${BUILDKITE_MATRIX_ARCH}"
      matrix:
        arch:
          - "amd64"
          - "386"
      artifact_paths: "pkg/*"
      plugins:
        docker-compose#v1.8.0:
          run: agent

  - wait

  - label: ":mag: Extract Version"
    command: ".buildkite/steps/extract-agent-version-metadata.sh"

  - wait

  - group: "Package "
    steps:
      - label: ":docker: Docker"
        command: ".buildkite/steps/build-docker-image.sh \${BUILDKITE_MATRIX_IMAGE}"
        matrix:
          image:
            - "alpine"
            - "ubuntu"

      - label: ":debian: Debian"
        command: ".buildkite/steps/build-debian-packages.sh"
        artifact_paths: "deb/**/*"
        agents:
          queue: "deploy"

      - label: ":redhat: Red Hat"
        command: ".buildkite/steps/build-rpm-packages.sh"
        artifact_paths: "rpm/**/*"
        agents:
          queue: "deploy"

      - label: ":github: GitHub Release"
        command: ".buildkite/steps/build-github-release.sh"
        artifact_paths: "releases/**/*"
        plugins:
          docker-compose#v1.8.0:
            config: docker-compose.release.yml
            run: github-release

  - wait

  - label: ":pipeline: Prepare Release"
    command: ".buildkite/steps/upload-release-steps.sh"
