steps:
  - block: ":shipit: Stable ${AGENT_VERSION}"

  - name: ":s3: publish binaries"
    command: "scripts/publish-to-s3.sh"
    env:
      CODENAME: "stable"
    agents:
      queue: "deploy"

  - name: ":redhat:"
    command: "scripts/rpm-package.sh"
    artifact_paths: "rpm/**/*"
    env:
      CODENAME: "stable"
    agents:
      queue: "deploy"

  - name: ":debian: publish stable"
    command: "scripts/publish-debian-package.sh"
    env:
      CODENAME: "stable"
    agents:
      queue: "deploy"

  - wait

  - name: ":whale: :rocket:"
    trigger: docker-buildkite-agent
    async: true
    build:
      message: "Update Docker images"
      commit: "HEAD"
      branch: "master"
      env:
        CODENAME: "stable"
