steps:
  - wait

  - block: ":shipit: ${AGENT_VERSION} to Unstable"
    branches: "master 2-1-stable"

  - name: ":s3: publish binaries"
    command: "scripts/publish-to-s3.sh"
    branches: "master 2-1-stable"
    env:
      CODENAME: "unstable"
    agents:
      queue: "deploy"

  - name: ":octocat: :rocket:"
    command: "scripts/github-release.sh"
    branches: "master 2-1-stable"
    agents:
      queue: "deploy"

  - name: ":redhat:"
    command: "scripts/rpm-package.sh"
    artifact_paths: "rpm/**/*"
    branches: "master 2-1-stable"
    env:
      CODENAME: "unstable"
    agents:
      queue: "deploy"

  - name: ":debian: publish unstable"
    command: "scripts/publish-debian-package.sh"
    branches: "master 2-1-stable"
    env:
      CODENAME: "unstable"
    agents:
      queue: "deploy"

  - wait

  - name: ":whale: :rocket:"
    trigger: docker-buildkite-agent
    branches: "master 2-1-stable"
    async: true
    build:
      message: "Update Docker images"
      commit: "HEAD"
      branch: "master"
      env:
        CODENAME: "unstable"

  - wait

  - name: ":beer:"
    command: "scripts/release-homebrew.sh"
    artifact_paths: "pkg/*.rb;pkg/*.json"
    agents:
      queue: "deploy"
