steps:
  -
    name: "🔨"
    command: "scripts/tests.sh"
    plugins:
      - file:///Users/tim/Codez/buildkite/docker-compose-buildkite-plugin.git:
          run: agent

  -
    name: "📦"
    command: "scripts/build-binaries.sh"
    artifact_paths: "pkg/*"
    plugins:
      - file:///Users/tim/Codez/buildkite/docker-compose-buildkite-plugin.git:
          run: agent
