steps:

  - name: ":hammer:"
    command: ".buildkite/steps/tests.sh"
    plugins:
      docker-compose#e8ce6c1:
        run: agent

  - wait

  - name: ":windows: 386"
    command: ".buildkite/steps/build-binary.sh windows 386"
    artifact_paths: "pkg/*"
    plugins:
      docker-compose#e8ce6c1:
        run: agent

  - name: ":windows: amd64"
    command: ".buildkite/steps/build-binary.sh windows amd64"
    artifact_paths: "pkg/*"
    plugins:
      docker-compose#e8ce6c1:
        run: agent

  - name: ":linux: amd64"
    command: ".buildkite/steps/build-binary.sh linux amd64"
    artifact_paths: "pkg/*"
    plugins:
      docker-compose#e8ce6c1:
        run: agent

  - name: ":linux: 386"
    command: ".buildkite/steps/build-binary.sh linux 386"
    artifact_paths: "pkg/*"
    plugins:
      docker-compose#e8ce6c1:
        run: agent

  - name: ":linux: arm"
    command: ".buildkite/steps/build-binary.sh linux arm"
    artifact_paths: "pkg/*"
    plugins:
      docker-compose#e8ce6c1:
        run: agent

  - name: ":linux: armhf"
    command: ".buildkite/steps/build-binary.sh linux armhf"
    artifact_paths: "pkg/*"
    plugins:
      docker-compose#e8ce6c1:
        run: agent

  - name: ":linux: arm64"
    command: ".buildkite/steps/build-binary.sh linux arm64"
    artifact_paths: "pkg/*"
    plugins:
      docker-compose#e8ce6c1:
        run: agent

  - name: ":mac: 386"
    command: ".buildkite/steps/build-binary.sh darwin 386"
    artifact_paths: "pkg/*"
    plugins:
      docker-compose#e8ce6c1:
        run: agent

  - name: ":mac: amd64"
    command: ".buildkite/steps/build-binary.sh darwin amd64"
    artifact_paths: "pkg/*"
    plugins:
      docker-compose#e8ce6c1:
        run: agent

  - name: ":freebsd: amd64"
    command: ".buildkite/steps/build-binary.sh freebsd amd64"
    artifact_paths: "pkg/*"
    plugins:
      docker-compose#e8ce6c1:
        run: agent

  - name: ":freebsd: 386"
    command: ".buildkite/steps/build-binary.sh freebsd 386"
    artifact_paths: "pkg/*"
    plugins:
      docker-compose#e8ce6c1:
        run: agent

  - wait

  - name: "Extract version metadata"
    command: ".buildkite/steps/extract-version-metadata.sh"
