steps:
  - wait

  - name: ":s3: publish binaries"
    command: "scripts/publish-to-s3.sh"
    branches: "master 2-1-stable"
    env:
      CODENAME: "experimental"
    agents:
      queue: "deploy"

  - name: ":redhat: experimental"
    command: "scripts/rpm-package.sh"
    artifact_paths: "rpm/**/*"
    branches: "master 2-1-stable"
    env:
      CODENAME: "experimental"
    agents:
      queue: "deploy"

  - name: ":debian: publish experimental"
    command: "scripts/publish-debian-package.sh"
    branches: "master 2-1-stable"
    env:
      CODENAME: "experimental"
    agents:
      queue: "deploy"

  - name: ":github: :hammer:"
    command: "scripts/build-github-release.sh"
    artifact_paths: "releases/**/*"
    branches: "master 2-1-stable"
    plugins:
      docker-compose#v1.5.0:
        config: docker-compose.release.yml
        run: github-release
