steps:
  -
    name: "🔨"
    command: "scripts/tests.sh"
    plugins:
      - https://github.com/buildkite/docker-compose-buildkite-plugin#8b2d39c:
          run: agent

  -
    name: "📦"
    command: "scripts/build-binaries.sh"
    artifact_paths: "pkg/*"
    plugins:
      - https://github.com/buildkite/docker-compose-buildkite-plugin#8b2d39c:
          run: agent
