steps:

  - name: ":hammer:"
    command: ".buildkite/steps/tests.sh"
    plugins:
      docker-compose#e8ce6c1:
        run: agent

  - wait

  - name: ":package: windows 386"
    command: ".buildkite/steps/build-binary.sh windows 386"
    artifact_paths: "pkg/*"
    plugins:
      docker-compose#e8ce6c1:
        run: agent

  - name: ":package: windows amd64"
    command: ".buildkite/steps/build-binary.sh windows amd64"
    artifact_paths: "pkg/*"
    plugins:
      docker-compose#e8ce6c1:
        run: agent

  - name: ":package: linux amd64"
    command: ".buildkite/steps/build-binary.sh linux amd64"
    artifact_paths: "pkg/*"
    plugins:
      docker-compose#e8ce6c1:
        run: agent

  - name: ":package: linux 386"
    command: ".buildkite/steps/build-binary.sh linux 386"
    artifact_paths: "pkg/*"
    plugins:
      docker-compose#e8ce6c1:
        run: agent

  - name: ":package: linux arm"
    command: "scripts/build-binary.sh linux arm"
    artifact_paths: "pkg/*"
    plugins:
      docker-compose#e8ce6c1:
        run: agent

  - name: ":package: linux armhf"
    command: "scripts/build-binary.sh linux armhf"
    artifact_paths: "pkg/*"
    plugins:
      docker-compose#e8ce6c1:
        run: agent

  - name: ":package: linux arm64"
    command: "scripts/build-binary.sh linux arm64"
    artifact_paths: "pkg/*"
    plugins:
      docker-compose#e8ce6c1:
        run: agent

  - name: ":package: darwin 386"
    command: "scripts/build-binary.sh darwin 386"
    artifact_paths: "pkg/*"
    plugins:
      docker-compose#e8ce6c1:
        run: agent

  - name: ":package: darwin amd64"
    command: "scripts/build-binary.sh darwin amd64"
    artifact_paths: "pkg/*"
    plugins:
      docker-compose#e8ce6c1:
        run: agent

  - name: ":package: freebsd amd64"
    command: "scripts/build-binary.sh freebsd amd64"
    artifact_paths: "pkg/*"
    plugins:
      docker-compose#e8ce6c1:
        run: agent

  - name: ":package: freebsd 386"
    command: "scripts/build-binary.sh freebsd 386"
    artifact_paths: "pkg/*"
    plugins:
      docker-compose#e8ce6c1:
        run: agent

  - wait

  - name: "Extract version metadata"
    command: "scripts/extract-version-metadata.sh"

  - wait

  -
    name: ":debian: build"
    command: "scripts/build-debian-packages.sh"
    artifact_paths: "deb/**/*"
    branches: "master 2-1-stable"
    agents:
      queue: "deploy"

  - wait

  -
    name: ":s3: publish binaries"
    command: "scripts/publish-to-s3.sh"
    branches: "master 2-1-stable"
    env:
      CODENAME: "experimental"
    agents:
      queue: "deploy"

  -
    name: ":redhat: experimental"
    command: "scripts/rpm-package.sh"
    artifact_paths: "rpm/**/*"
    branches: "master 2-1-stable"
    env:
      CODENAME: "experimental"
    agents:
      queue: "deploy"

  -
    name: ":debian: publish experimental"
    command: "scripts/publish-debian-package.sh"
    branches: "master 2-1-stable"
    env:
      CODENAME: "experimental"
    agents:
      queue: "deploy"

  -
    name: ":github: :hammer:"
    command: "scripts/build-github-release.sh"
    artifact_paths: "releases/**/*"
    branches: "master 2-1-stable"
    agents:
      # TODO: Remove
      queue: "legacy-ci"

  - wait

  -
    name: ":whale:"
    command: "scripts/release-docker.sh"
    branches: "master 2-1-stable"
    agents:
      queue: "deploy"

  - block: ":shipit: Unstable"
    branches: "master 2-1-stable"

  -
    name: ":s3: publish binaries"
    command: "scripts/publish-to-s3.sh"
    branches: "master 2-1-stable"
    env:
      CODENAME: "unstable"
    agents:
      queue: "deploy"

  -
    name: ":octocat: :rocket:"
    command: "scripts/github-release.sh"
    branches: "master 2-1-stable"
    agents:
      queue: "deploy"

  -
    name: ":redhat:"
    command: "scripts/rpm-package.sh"
    artifact_paths: "rpm/**/*"
    branches: "master 2-1-stable"
    env:
      CODENAME: "unstable"
    agents:
      queue: "deploy"

  -
    name: ":debian: publish unstable"
    command: "scripts/publish-debian-package.sh"
    branches: "master 2-1-stable"
    env:
      CODENAME: "unstable"
    agents:
      queue: "deploy"

  - wait

  -
    name: ":whale:"
    command: "scripts/release-docker.sh"
    branches: "master 2-1-stable"
    agents:
      queue: "deploy"

  -
    name: ":beer:"
    command: "scripts/release-homebrew.sh"
    artifact_paths: "pkg/*.rb;pkg/*.json"
    branches: "master 2-1-stable"
    agents:
      queue: "deploy"

  - block: ":shipit: Stable"
    branches: "master 2-1-stable"

  -
    name: ":s3: publish binaries"
    command: "scripts/publish-to-s3.sh"
    branches: "master 2-1-stable"
    env:
      CODENAME: "stable"
    agents:
      queue: "deploy"

  -
    name: ":redhat:"
    command: "scripts/rpm-package.sh"
    artifact_paths: "rpm/**/*"
    branches: "master 2-1-stable"
    env:
      CODENAME: "stable"
    agents:
      queue: "deploy"

  -
    name: ":debian: publish stable"
    command: "scripts/publish-debian-package.sh"
    branches: "master 2-1-stable"
    env:
      CODENAME: "stable"
    agents:
      queue: "deploy"

  - wait

  -
    name: ":whale:"
    command: "scripts/release-docker.sh"
    branches: "master 2-1-stable"
    agents:
      queue: "deploy"
